[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files", args = [
    "--maxkb=1024",
  ] },
  { id = "check-json" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.19.1"  # Replace with the latest version tag or commit SHA
hooks = [
    { id = "pyupgrade", args = ["--py311-plus"] }
]

